---
- name: create or update stack resources
  cloudformation:
    stack_name: "{{ project_name }}-network-stack-{{ env }}"
    state: "present"
    disable_rollback: false
    region: '{{ aws.region }}'
    template: "{{ role_path }}/files/stack_template.yaml"
    template_parameters: '{{ template_parameters }}'
    tags:
      Env: "{{ env }}"
    stack_policy: "{{ role_path }}/files/stack_policy.json"
  register: "networkStack"

- name: read stack output
  set_fact:
    network_stack:
      stack_output: "{{ networkStack.stack_outputs }}"
